spin_manifest_version = "1"
authors = ["Mikkel Mørk Hegnhøj <mikkel@fermyon.com>"]
description = "4-ben"
name = "sumpskildpadde"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "sumpskildpadde"
source = "app.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "spin py2wasm app -o app.wasm"
